# Generated by Django 4.2.2 on 2023-08-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.CharField(blank=True, max_length=500)),
                ('datum', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItPojem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zkratka', models.SlugField(max_length=100)),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('nazev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.SlugField(max_length=100)),
                ('obsah', models.CharField(max_length=500)),
                ('clanek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='it_pojmy.clanek')),
            ],
        ),
        migrations.AddField(
            model_name='clanek',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='it_pojmy.kategorie'),
        ),
    ]
