# Generated by Django 4.2.2 on 2023-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_pojmy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('nazev', models.CharField(max_length=100)),
                ('obsah', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
