# Generated by Django 4.2.2 on 2023-08-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_pojmy', '0002_alter_clanek_datum_alter_komentar_clanek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='clanek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='komentare_clanku', to='it_pojmy.clanek'),
        ),
    ]
