# Generated by Django 4.2.2 on 2023-08-02 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_pojmy', '0003_clanek_datum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('nazev', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clanek',
            name='obsah',
        ),
        migrations.AddField(
            model_name='clanek',
            name='popis',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='clanek',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='clanek',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='it_pojmy.kategorie'),
        ),
    ]
