# Generated by Django 4.2.2 on 2023-08-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_pojmy', '0004_kategorie_remove_clanek_obsah_clanek_popis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.SlugField(max_length=100)),
                ('obsah', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='clanek',
            name='komentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='it_pojmy.komentar'),
        ),
    ]
